language: java

services:
  - docker

before_install:
- docker build -t conductor .
- docker run -d -p 127.0.0.1:5000:8000 conductor /bin/sh -c "pwd"
- docker ps -a
- docker run conductor /bin/sh -c "pwd"

script:
- "curl -s http://conductor:5000"